import {Team, Color} from "./general.js";
import {SubWeapon, SpecialWeapon, MainWeapon, MAIN_TYPES} from "./weaponsClass.js";

export const SPECIAL_WEAPONS = {
    BigBubbler: new SpecialWeapon("Big Bubbler", "big_bubbler"),
    BooyahBomb: new SpecialWeapon("Booyah Bomb", "booyah_bomb"),
    CrabTank: new SpecialWeapon("Crab Tank", "crab_tank"),
    InkJet: new SpecialWeapon("Ink Het", "ink_jet"),
    InkStorm: new SpecialWeapon("Ink Storm", "ink_storm"),
    InkVac: new SpecialWeapon("Ink Vac", "ink_vac"),
    KillerWail: new SpecialWeapon("Killer Wail 5.1", "killer_wail_5_1"),
    KrakenRoyale: new SpecialWeapon("Kraken Royale", "kraken_royale"),
    ReefSlider: new SpecialWeapon("Reef Slider", "reef_slider"),
    SplattercolorScreen: new SpecialWeapon("Splattercolor Screen", "splattercolor_screen"),
    SuperChump: new SpecialWeapon("Super Chump", "super_chump"),
    Tacticooler: new SpecialWeapon("Tacticooler", "tacticooler"),
    TentaMissiles: new SpecialWeapon("Tenta Missiles", "tenta_missiles"),
    TripleInkstrike: new SpecialWeapon("Triple Inkstrike", "triple_inkstrike"),
    TripleSplashdown: new SpecialWeapon("Triple Splashdown", "triple_splashdown"),
    Trizooka: new SpecialWeapon("Trizooka", "trizooka"),
    UltraStamp: new SpecialWeapon("Ultra Stamp", "ultra_stamp"),
    WaveBreaker: new SpecialWeapon("Wave Breaker", "wave_breaker"),
    Zipcaster: new SpecialWeapon("Zipcaster", "zipcaster"),
}
export const SUB_WEAPONS = {
    AngleShooter: new SubWeapon("Angle Shooter", "angle_shooter"),
    AutoBomb: new SubWeapon("Auto Bomb", "auto_bomb"),
    BurstBomb: new SubWeapon("Burst Bomb", "burst_bomb"),
    CurlingBomb: new SubWeapon("Curling Bomb", "curling_bomb"),
    FizzyBomb: new SubWeapon("Fizzy Bomb", "fizzy_bomb"),
    InkMine: new SubWeapon("Ink Mine", "ink_mine"),
    PointSensorr: new SubWeapon("Point Sensor", "point_sensor"),
    SplatBomb: new SubWeapon("Splat Bomb", "splat_bomb"),
    Sprinkler: new SubWeapon("Sprinkler", "sprinkler"),
    SquidBeakon: new SubWeapon("Squid Beakon", "squid_beakon"),
    SuctionBomb: new SubWeapon("Suction Bomb", "suction_bomb"),
    Torpedo: new SubWeapon("Torpedo", "torpedo"),
    ToxicMist: new SubWeapon("Toxic Mist", "toxic_mist"),
}
export const TEAMS = {
    BlueYellow: new Team("BlueYellow", "Splatoon 3", new Color(26,26,174), new Color(227,141,36)),
    GreenPurple: new Team("GreenPurple", "Splatoon 3", new Color(160,201,55), new Color(174,0,174)),
    LimegreenPurple: new Team("LimegreenPurple", "Splatoon 3", new Color(190,205,65), new Color(99,37,205)),
    OrangeBlue: new Team("OrangeBlue", "Splatoon 1", new Color(222, 102, 36), new Color(52,59,196)),
    OrangePurple: new Team("OrangePurple", "Splatoon 3", new Color(222, 102, 36), new Color(110,4,182)),
    PinkGreen: new Team("PinkGreen", "Splatoon 2", new Color(193,45,116), new Color(44,183,33)),
    TurquoisePink: new Team("TurquoisePink", "Splatoon 3", new Color(27,190,171), new Color(196,58,110)),
    TurquoiseRed: new Team("TurquoiseRed", "Splatoon 3", new Color(30,192,173), new Color(215,75,49)),
    YellowBlue: new Team("YellowBlue", "Splatoon 3", new Color(208,190,8), new Color(58,12,205)),
    YellowPurple: new Team("YellowPurple", "Splatoon 3", new Color(206,177,33), new Color(144,37,198)),
}

export const MAIN_WEAPONS = {
    GalDeco52: new MainWeapon(".52 Gal Deco", MAIN_TYPES.Shooter, "52_gal_deco"),
    Gal52: new MainWeapon(".52 Gal", MAIN_TYPES.Shooter, "52_gal"),
    GalDeco96: new MainWeapon(".96 Gal Deco", MAIN_TYPES.Shooter, "96_gal_deco"),
    Gal96: new MainWeapon(".96 Gal", MAIN_TYPES.Shooter, "96_gal"),
    AerosprayMG: new MainWeapon("Aerospray MG", MAIN_TYPES.Shooter, "aerospray_mg"),
    AerosprayRG: new MainWeapon("Aerospray RG", MAIN_TYPES.Shooter, "aerospray_rg"),
    AnnakiSplattershotNova: new MainWeapon("Annaki Splattershot Nova", MAIN_TYPES.Shooter, "annaki_splattershot_nova"),
    BallpointSplatlingNouveau: new MainWeapon("Ballpoint Splatling Nouveau", MAIN_TYPES.Splatling, "ballpoint_splatling_nouveau"),
    BallpointSplatling: new MainWeapon("Ballpoint Splatling", MAIN_TYPES.Splatling, "ballpoint_splatling"),
    Bamboozler14MI: new MainWeapon("Bamboozler 14 Mk I", MAIN_TYPES.Charger, "bamboozler_14_mk_I"),
    Bamboozler14MkII: new MainWeapon("Bamboozler 14 Mk II", MAIN_TYPES.Charger, "bamboozler_14_mk_ii"),
    BigSwigRollerExpress: new MainWeapon("Big Swig Roller Express", MAIN_TYPES.Roller, "big_swig_roller_express"),
    BigSwigRoller: new MainWeapon("Big Swig Roller", MAIN_TYPES.Roller, "big_swig_roller"),
    Blaster: new MainWeapon("Blaster", MAIN_TYPES.Blaster, "blaster"),
    BloblobberDeco: new MainWeapon("Bloblobber Deco", MAIN_TYPES.Slosher, "bloblobber_deco"),
    Bloblobber: new MainWeapon("Bloblobber", MAIN_TYPES.Slosher, "bloblobber"),
    CarbonRollerDeco: new MainWeapon("Carbon Roller Deco", MAIN_TYPES.Roller, "carbon_roller_deco"),
    CarbonRoller: new MainWeapon("Carbon Roller", MAIN_TYPES.Roller, "carbon_roller"),
    CharcoalDecavitator: new MainWeapon("Charcoal Decavitator", MAIN_TYPES.Splatana, "charcoal_decavitator"),
    ClashBlaster: new MainWeapon("Clash Blaster", MAIN_TYPES.Blaster, "clash_blaster"),
    ClashBlasterNeo: new MainWeapon("Clash Blaster Neo", MAIN_TYPES.Blaster, "clash_blaster_neo"),
    ClassicSquiffer: new MainWeapon("Classic Squiffer", MAIN_TYPES.Charger, "classic_squiffer"),
    CustomBlaster: new MainWeapon("Custom Blaster", MAIN_TYPES.Blaster, "custom_blaster"),
    CustomDouserDualiesFF: new MainWeapon("Custom Douser Dualies FF", MAIN_TYPES.Dualies, "custom_douser_dualies_ff"),
    CustmDualieSquelchers: new MainWeapon("Custom Dualie Squelchers", MAIN_TYPES.Dualies, "custom_dualie_squelchers"),
    CustomELiter4KScope: new MainWeapon("Custom E-liter 4K Scope", MAIN_TYPES.Charger, "custom_e_liter_4k_scope"),
    CustomELiter4k:  new MainWeapon("Custom E-liter 4K", MAIN_TYPES.Charger, "custom_e_liter_4k"),
    CustomExplosher: new MainWeapon("Custom Explosher", MAIN_TYPES.Slosher, "custom_explosher"),
    CustomGooTuber: new MainWeapon("Custom Goo Tuber", MAIN_TYPES.Charger, "custom_goo_tuber"),
    CustomHydraSplatling: new MainWeapon("Custom Hydra Splatling", MAIN_TYPES.Splatling, "custom_hydra_splatling"),
    CustomJetSquelcher: new MainWeapon("Custom Jet Squelcher", MAIN_TYPES.Slosher, "custom_jet_squelcher"),
    CustomRangeBlaster: new MainWeapon("Custom Range Blaster", MAIN_TYPES.Blaster, "custom_range_blaster"),
    CustomSplattershotJR: new MainWeapon("Custom Splattershot Jr.", MAIN_TYPES.Shooter, "custom_splattershot_jr"),
    CustomWellstringV: new MainWeapon("Custom Wellstring V", MAIN_TYPES.Stringer, "custom_wellstring_v"),
    DappleDualiesNouveau: new MainWeapon("Dapple Dualies Nouveau", MAIN_TYPES.Dualies, "dapple_dualies_nouveau"),
    DappleDualies: new MainWeapon("Dapple Dualies", MAIN_TYPES.Dualies, "dapple_dualies"),
    DreadWringerD: new MainWeapon("Dread Wringer D", MAIN_TYPES.Slosher, "dread_wringer_d"),
    DreadWringer: new MainWeapon("Dread Wringer", MAIN_TYPES.Slosher, "dread_wringer"),
    DualieSquelchers: new MainWeapon("Dualie Squelchers", MAIN_TYPES.Dualies, "dualie_squelchers"),
    DynamoRoller: new MainWeapon("Dynamo Roller", MAIN_TYPES.Roller, "dynamo_roller"),
    Eliter4KScope: new MainWeapon("E-liter 4K Scope", MAIN_TYPES.Charger, "e_liter_4k_scope"),
    Eliter4k: new MainWeapon("E-liter 4K", MAIN_TYPES.Charger, "e_liter_4k"),
    EnperrySplatDualies: new MainWeapon("Enperry Splat Dualies", MAIN_TYPES.Dualies, "enperry_splat_dualies"),
    Explosher: new MainWeapon("Explosher", MAIN_TYPES.Slosher, "explosher"),
    FoilFlingzaRoller: new MainWeapon("Foil Flingza Roller", MAIN_TYPES.Roller, "foil_flingza_roller"),
    FoilSqueezer: new MainWeapon("Foil Squeezer", MAIN_TYPES.Shooter, "foil_squeezer"),
    GloogaDualiesDeco: new MainWeapon("Glooga Dualies Deco", MAIN_TYPES.Dualies, "glooga_dualies_deco"),
    GloogaDualies: new MainWeapon("Glooga Dualies", MAIN_TYPES.Dualies, "glooga_dualies"),
    GooTuber: new MainWeapon("Goo Tuber", MAIN_TYPES.Charger, "goo_tuber"),
    H3Nozzelnose: new MainWeapon("H-3 Nozzelnose", MAIN_TYPES.Shooter, "h_3_nozzelnose"),
    H3NozzelnoseD: new MainWeapon("H-3 Nozzelnose D", MAIN_TYPES.Shooter, "h_3_nozzelnose_d"),
    HeavyEditSplatling: new MainWeapon("Heavy Edit Splatling", MAIN_TYPES.Splatling, "heavy_edit_splatling"),
    HeavyEditSplatlingNouveau: new MainWeapon("Heavy Edit Splatling Nouveau", MAIN_TYPES.Splatling, "heavy_edit_splatling_nouveau"),
    HeavySplatlingDeco: new MainWeapon("Heavy Splatling Deco", MAIN_TYPES.Splatling, "heavy_splatling_deco"),
    HeavySplatling: new MainWeapon("Heavy Splatling", MAIN_TYPES.Splatling, "heavy_splatling"),
    HeroShotReplica: new MainWeapon("Hero Shot Replica", MAIN_TYPES.Shooter, "hero_shot_replica"),
    HydraSplatling: new MainWeapon("Hydra Splatling", MAIN_TYPES.Splatling, "hydra_splatling"),
    InkbrushNouveau: new MainWeapon("Inkbrush Nouveau", MAIN_TYPES.Brush, "inkbrush_nouveau"),
    Inkbrush: new MainWeapon("Inkbrush", MAIN_TYPES.Brush, "inkbrush"),
    InklineTriStringer: new MainWeapon("Inkline Tri-stringer", MAIN_TYPES.Stringer, "inkline_tri_stringer"),
    JetSquelcher: new MainWeapon("Jet Squelcher", MAIN_TYPES.Shooter, "jet_squelcher"),
    KrakOnSplatRoller: new MainWeapon("Krak-On Splat Roller", MAIN_TYPES.Roller, "krak_on_splat_roller"),
    L3NozzlenoseD: new MainWeapon("L-3 Nozzelnose D", MAIN_TYPES.Shooter, "l_3_nozzelnose_d"),
    L3Nozzlenose: new MainWeapon("L-3 Nozzelnose", MAIN_TYPES.Shooter, "l_3_nozzelnose"),
    LightTetraDualies: new MainWeapon("Light Tetra Dualies", MAIN_TYPES.Dualies, "light_tetra_dualies"),
    LunaBlasterNeo: new MainWeapon("Luna Blaster Neo", MAIN_TYPES.Blaster, "luna_blaster_neo"),
    LunaBlaster: new MainWeapon("Luna Blaster", MAIN_TYPES.Blaster, "luna_blaster"),
    MiniSplatling: new MainWeapon("Mini Splatling", MAIN_TYPES.Splatling, "mini_splatling"),
    MintDecavitator: new MainWeapon("Mint Decavitator", MAIN_TYPES.Splatana, "mint_decavitator"),
    NZap85: new MainWeapon("N-ZAP '85", MAIN_TYPES.Shooter, "n_zap_85"),
    NZap89: new MainWeapon("N-ZAP '89", MAIN_TYPES.Shooter, "n_zap_89"),
    Nautilus47: new MainWeapon("Nautilus 47", MAIN_TYPES.Splatling, "nautilus_47"),
    Nautilus79: new MainWeapon("Nautilus 79", MAIN_TYPES.Splatling, "nautilus_79"),
    NeoSplashOMatic: new MainWeapon("Neo Splash-o-matic", MAIN_TYPES.Shooter, "neo_splash_o_matic"),
    NewSquiffer: new MainWeapon("New Squiffer", MAIN_TYPES.Charger, "new_squiffer"),
    OctoShotReplica: new MainWeapon("Octo Shot Replica", MAIN_TYPES.Shooter, "octo_shot_replica"),
    OctobrushNouveau: new MainWeapon("Octobrush Nouveau", MAIN_TYPES.Brush, "octobrush_nouveau"),
    Octobrush: new MainWeapon("Octobrush", MAIN_TYPES.Brush, "octobrush"),
    OrderBlasterReplica: new MainWeapon("Order Blaster Replica", MAIN_TYPES.Blaster, "order_blaster_replica"),
    OrderChargerReplica: new MainWeapon("Order Charger Replica", MAIN_TYPES.Charger, "order_charger_replica"),
    OrderDualieReplicas: new MainWeapon("Order Dualie Replicas", MAIN_TYPES.Dualies, "order_dualie_replicas"),
    OrderRollerReplica: new MainWeapon("Order Roller Replica", MAIN_TYPES.Roller, "order_roller_replica"),
    OrderShotReplica: new MainWeapon("Order Shot Replica", MAIN_TYPES.Shooter, "order_shot_replica"),
    OrderSlosherReplica: new MainWeapon("Order Slosher Replica", MAIN_TYPES.Slosher, "order_slosher_replica"),
    OrderSplatanaReplica: new MainWeapon("Order Splatana Replica", MAIN_TYPES.Splatana, "order_splatana_replica"),
    OrderSplatlingReplica: new MainWeapon("Order Splatling Replica", MAIN_TYPES.Splatling, "order_splatling_replica"),
    OrderStringerReplica: new MainWeapon("Order Stringer Replica", MAIN_TYPES.Stringer, "order_stringer_replica"),
    OrderBrushReplica: new MainWeapon("Order Brush Replica", MAIN_TYPES.Brush, "order_brush_replica"),
    PainbrushNouveau: new MainWeapon("Painbrush Nouveau", MAIN_TYPES.Brush, "painbrush_nouveau"),
    Painbrush: new MainWeapon("Painbrush", MAIN_TYPES.Brush, "painbrush"),
    RangeBlaster: new MainWeapon("Range Blaster", MAIN_TYPES.Blaster, "range_blaster"),
    RapidBlasterDeco: new MainWeapon("Rapid Blaster Deco", MAIN_TYPES.Blaster, "rapid_blaster_deco"),
    RapidBlaster: new MainWeapon("Rapid Blaster", MAIN_TYPES.Blaster, "rapid_blaster"),
    RapidBlasterPro: new MainWeapon("Rapid Blaster Pro", MAIN_TYPES.Blaster, "rapid_blaster_pro"),
    RapidBlasterProDeco: new MainWeapon("Rapid Blaster Pro Deco", MAIN_TYPES.Blaster, "rapid_blaster_pro_deco"),
    RecycledBrella24MKI: new MainWeapon("Recycled Brella 24 MK I", MAIN_TYPES.Brella, "recycled_brella_24_mk_i"),
    RecycledBrella24MKII: new MainWeapon("Recycled Brella 24 MK II", MAIN_TYPES.Brella, "recycled_brella_24_mk_ii"),
    ReefLux450Deco: new MainWeapon("Reef Lux 450 Deco", MAIN_TYPES.Stringer, "reef_lux_450_deco"),
    ReefLux450: new MainWeapon("Reef Lux 450", MAIN_TYPES.Stringer, "reef_lux_450"),
    SBlast91: new MainWeapon("S-Blast '91", MAIN_TYPES.Blaster, "s_blast_91"),
    SBlast92: new MainWeapon("S-Blast '92", MAIN_TYPES.Blaster, "s_blast_92"),
    SlosherDeco: new MainWeapon("Slosher Deco", MAIN_TYPES.Slosher, "slosher_deco"),
    Slosher: new MainWeapon("Slosher", MAIN_TYPES.Slosher, "slosher"),
    SloshingMachineNeo: new MainWeapon("Sloshing Machine Neo", MAIN_TYPES.Slosher, "sloshing_machine_neo"),
    SloshingMachine: new MainWeapon("Sloshing Machine", MAIN_TYPES.Slosher, "sloshing_machine"),
    Snipewriter5H: new MainWeapon("Snipewriter 5H", MAIN_TYPES.Charger, "snipewriter_5h"),
    Smipewriter5B: new MainWeapon("Snipewriter 5B", MAIN_TYPES.Charger, "snipewriter_5b"),
    SorellaBrella: new MainWeapon("Sorella Brella", MAIN_TYPES.Brella, "sorella_brella"),
    SplatBrella: new MainWeapon("Splat Brella", MAIN_TYPES.Brella, "splat_brella"),
    SplatCharger: new MainWeapon("Splat Charger", MAIN_TYPES.Charger, "splat_charger"),
    SplatDualies: new MainWeapon("Splat Dualies", MAIN_TYPES.Dualies, "splat_dualies"),
    SplashOMatic: new MainWeapon("Splash-o-matic", MAIN_TYPES.Shooter, "splash_o_matic"),
    SplatRoller: new MainWeapon("Splat Roller", MAIN_TYPES.Roller, "splat_roller"),
    SplatanaStamperNouveau: new MainWeapon("Splatana Stamper Nouveau", MAIN_TYPES.Splatana, "splatana_stamper_nouveau"),
    SplatanaStamper: new MainWeapon("Splatana Stamper", MAIN_TYPES.Splatana, "splatana_stamper"),
    SplatanaWiperDeco: new MainWeapon("Splatana Wiper Deco", MAIN_TYPES.Splatana, "splatana_wiper_deco"),
    SplatanaWiper: new MainWeapon("Splatana Wiper", MAIN_TYPES.Splatana, "splatana_wiper"),
    Splatterscope: new MainWeapon("Splatterscope", MAIN_TYPES.Charger, "splatterscope"),
    SplattershotJR: new MainWeapon("Splattershot Jr.", MAIN_TYPES.Shooter, "splattershot_jr"),
    SplattershotNova: new MainWeapon("Splattershot Nova", MAIN_TYPES.Shooter, "splattershot_nova"),
    SplattershotPro: new MainWeapon("Splattershot Pro", MAIN_TYPES.Shooter, "splattershot_pro"),
    Splattershot: new MainWeapon("Splattershot", MAIN_TYPES.Shooter, "splattershot"),
    SplooshOMatic: new MainWeapon("Sploosh-o-matic", MAIN_TYPES.Shooter, "sploosh_o_matic"),
    Squeezer: new MainWeapon("Squeezer", MAIN_TYPES.Shooter, "squeezer"),
    TentaBrella: new MainWeapon("Tenta Brella", MAIN_TYPES.Brella, "tenta_brella"),
    TentatekSplattershot: new MainWeapon("Tentatek Splattershot", MAIN_TYPES.Shooter, "tentatek_splattershot"),
    TriSlosherNouveau: new MainWeapon("Tri-Slosher Nouveau", MAIN_TYPES.Slosher, "tri_slosher_nouveau"),
    TriSlosher: new MainWeapon("Tri-Slosher", MAIN_TYPES.Slosher, "tri_slosher"),
    TriStringer: new MainWeapon("Tri-Stringer", MAIN_TYPES.Stringer, "tri_stringer"),
    UndercoverBrella: new MainWeapon("Undercover Brella", MAIN_TYPES.Brella, "undercover_brella"),
    UndercoverSorellaBrella: new MainWeapon("Undercover Sorella Brella", MAIN_TYPES.Brella, "undercover_sorella_brella"),
    WellstringV: new MainWeapon("Wellstring V", MAIN_TYPES.Stringer, "wellstring_v"),
    ZnFSplatCharger: new MainWeapon("Z+F Splat Charger", MAIN_TYPES.Charger, "z+f_splat_charger"),
    ZnFSplatterscope: new MainWeapon("Z+F Splatterscope", MAIN_TYPES.Charger, "z+f_splatterscope"),
    ZinkMiniSplatling: new MainWeapon("Zink Mini Splatling", MAIN_TYPES.Splatling, "zink_mini_splatling"),
}
